<?php

namespace DoctrineProxies\__CG__;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class User extends \User implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'User' . "\0" . 'id', '' . "\0" . 'User' . "\0" . 'sitecode', '' . "\0" . 'User' . "\0" . 'eventcode', '' . "\0" . 'User' . "\0" . 'firstname', '' . "\0" . 'User' . "\0" . 'lastname', '' . "\0" . 'User' . "\0" . 'phone', '' . "\0" . 'User' . "\0" . 'mobile', '' . "\0" . 'User' . "\0" . 'zipcode', '' . "\0" . 'User' . "\0" . 'email', '' . "\0" . 'User' . "\0" . 'gamecode', '' . "\0" . 'User' . "\0" . 'teamcode', '' . "\0" . 'User' . "\0" . 'teamplayercode', '' . "\0" . 'User' . "\0" . 'isremotesynced', '' . "\0" . 'User' . "\0" . 'reserve1', '' . "\0" . 'User' . "\0" . 'reserve2', '' . "\0" . 'User' . "\0" . 'reserve3', '' . "\0" . 'User' . "\0" . 'reserve4', '' . "\0" . 'User' . "\0" . 'reserve5', '' . "\0" . 'User' . "\0" . 'videoid', '' . "\0" . 'User' . "\0" . 'photoid', '' . "\0" . 'User' . "\0" . 'localid', '' . "\0" . 'User' . "\0" . 'localsitecode', '' . "\0" . 'User' . "\0" . 'localcreatedate', '' . "\0" . 'User' . "\0" . 'isapproved', '' . "\0" . 'User' . "\0" . 'approveddate', '' . "\0" . 'User' . "\0" . 'approveduser', '' . "\0" . 'User' . "\0" . 'issentemail', '' . "\0" . 'User' . "\0" . 'issentsns', '' . "\0" . 'User' . "\0" . 'createdate', '' . "\0" . 'User' . "\0" . 'createuser', '' . "\0" . 'User' . "\0" . 'updatedate', '' . "\0" . 'User' . "\0" . 'updateuser', '' . "\0" . 'User' . "\0" . 'valid', '' . "\0" . 'User' . "\0" . 'projectcode', '' . "\0" . 'User' . "\0" . 'isfavorite', '' . "\0" . 'User' . "\0" . 'medias', '' . "\0" . 'User' . "\0" . 'sendsnses', '' . "\0" . 'User' . "\0" . 'emaillogs');
        }

        return array('__isInitialized__', '' . "\0" . 'User' . "\0" . 'id', '' . "\0" . 'User' . "\0" . 'sitecode', '' . "\0" . 'User' . "\0" . 'eventcode', '' . "\0" . 'User' . "\0" . 'firstname', '' . "\0" . 'User' . "\0" . 'lastname', '' . "\0" . 'User' . "\0" . 'phone', '' . "\0" . 'User' . "\0" . 'mobile', '' . "\0" . 'User' . "\0" . 'zipcode', '' . "\0" . 'User' . "\0" . 'email', '' . "\0" . 'User' . "\0" . 'gamecode', '' . "\0" . 'User' . "\0" . 'teamcode', '' . "\0" . 'User' . "\0" . 'teamplayercode', '' . "\0" . 'User' . "\0" . 'isremotesynced', '' . "\0" . 'User' . "\0" . 'reserve1', '' . "\0" . 'User' . "\0" . 'reserve2', '' . "\0" . 'User' . "\0" . 'reserve3', '' . "\0" . 'User' . "\0" . 'reserve4', '' . "\0" . 'User' . "\0" . 'reserve5', '' . "\0" . 'User' . "\0" . 'videoid', '' . "\0" . 'User' . "\0" . 'photoid', '' . "\0" . 'User' . "\0" . 'localid', '' . "\0" . 'User' . "\0" . 'localsitecode', '' . "\0" . 'User' . "\0" . 'localcreatedate', '' . "\0" . 'User' . "\0" . 'isapproved', '' . "\0" . 'User' . "\0" . 'approveddate', '' . "\0" . 'User' . "\0" . 'approveduser', '' . "\0" . 'User' . "\0" . 'issentemail', '' . "\0" . 'User' . "\0" . 'issentsns', '' . "\0" . 'User' . "\0" . 'createdate', '' . "\0" . 'User' . "\0" . 'createuser', '' . "\0" . 'User' . "\0" . 'updatedate', '' . "\0" . 'User' . "\0" . 'updateuser', '' . "\0" . 'User' . "\0" . 'valid', '' . "\0" . 'User' . "\0" . 'projectcode', '' . "\0" . 'User' . "\0" . 'isfavorite', '' . "\0" . 'User' . "\0" . 'medias', '' . "\0" . 'User' . "\0" . 'sendsnses', '' . "\0" . 'User' . "\0" . 'emaillogs');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (User $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getMedias()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMedias', array());

        return parent::getMedias();
    }

    /**
     * {@inheritDoc}
     */
    public function getSendSNSes()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSendSNSes', array());

        return parent::getSendSNSes();
    }

    /**
     * {@inheritDoc}
     */
    public function getEmailLogs()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmailLogs', array());

        return parent::getEmailLogs();
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setSitecode($sitecode)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSitecode', array($sitecode));

        return parent::setSitecode($sitecode);
    }

    /**
     * {@inheritDoc}
     */
    public function getSitecode()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSitecode', array());

        return parent::getSitecode();
    }

    /**
     * {@inheritDoc}
     */
    public function setEventcode($eventcode)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEventcode', array($eventcode));

        return parent::setEventcode($eventcode);
    }

    /**
     * {@inheritDoc}
     */
    public function getEventcode()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEventcode', array());

        return parent::getEventcode();
    }

    /**
     * {@inheritDoc}
     */
    public function setFirstname($firstname)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFirstname', array($firstname));

        return parent::setFirstname($firstname);
    }

    /**
     * {@inheritDoc}
     */
    public function getFirstname()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFirstname', array());

        return parent::getFirstname();
    }

    /**
     * {@inheritDoc}
     */
    public function setLastname($lastname)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLastname', array($lastname));

        return parent::setLastname($lastname);
    }

    /**
     * {@inheritDoc}
     */
    public function getLastname()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLastname', array());

        return parent::getLastname();
    }

    /**
     * {@inheritDoc}
     */
    public function setPhone($phone)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPhone', array($phone));

        return parent::setPhone($phone);
    }

    /**
     * {@inheritDoc}
     */
    public function getPhone()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPhone', array());

        return parent::getPhone();
    }

    /**
     * {@inheritDoc}
     */
    public function setMobile($mobile)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMobile', array($mobile));

        return parent::setMobile($mobile);
    }

    /**
     * {@inheritDoc}
     */
    public function getMobile()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMobile', array());

        return parent::getMobile();
    }

    /**
     * {@inheritDoc}
     */
    public function setZipcode($zipcode)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setZipcode', array($zipcode));

        return parent::setZipcode($zipcode);
    }

    /**
     * {@inheritDoc}
     */
    public function getZipcode()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getZipcode', array());

        return parent::getZipcode();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmail($email)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmail', array($email));

        return parent::setEmail($email);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmail', array());

        return parent::getEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function setGamecode($gamecode)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGamecode', array($gamecode));

        return parent::setGamecode($gamecode);
    }

    /**
     * {@inheritDoc}
     */
    public function getGamecode()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGamecode', array());

        return parent::getGamecode();
    }

    /**
     * {@inheritDoc}
     */
    public function setTeamcode($teamcode)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTeamcode', array($teamcode));

        return parent::setTeamcode($teamcode);
    }

    /**
     * {@inheritDoc}
     */
    public function getTeamcode()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTeamcode', array());

        return parent::getTeamcode();
    }

    /**
     * {@inheritDoc}
     */
    public function setTeamplayercode($teamplayercode)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTeamplayercode', array($teamplayercode));

        return parent::setTeamplayercode($teamplayercode);
    }

    /**
     * {@inheritDoc}
     */
    public function getTeamplayercode()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTeamplayercode', array());

        return parent::getTeamplayercode();
    }

    /**
     * {@inheritDoc}
     */
    public function setIsremotesynced($isremotesynced)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsremotesynced', array($isremotesynced));

        return parent::setIsremotesynced($isremotesynced);
    }

    /**
     * {@inheritDoc}
     */
    public function getIsremotesynced()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIsremotesynced', array());

        return parent::getIsremotesynced();
    }

    /**
     * {@inheritDoc}
     */
    public function setReserve1($reserve1)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setReserve1', array($reserve1));

        return parent::setReserve1($reserve1);
    }

    /**
     * {@inheritDoc}
     */
    public function getReserve1()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getReserve1', array());

        return parent::getReserve1();
    }

    /**
     * {@inheritDoc}
     */
    public function setReserve2($reserve2)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setReserve2', array($reserve2));

        return parent::setReserve2($reserve2);
    }

    /**
     * {@inheritDoc}
     */
    public function getReserve2()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getReserve2', array());

        return parent::getReserve2();
    }

    /**
     * {@inheritDoc}
     */
    public function setReserve3($reserve3)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setReserve3', array($reserve3));

        return parent::setReserve3($reserve3);
    }

    /**
     * {@inheritDoc}
     */
    public function getReserve3()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getReserve3', array());

        return parent::getReserve3();
    }

    /**
     * {@inheritDoc}
     */
    public function setReserve4($reserve4)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setReserve4', array($reserve4));

        return parent::setReserve4($reserve4);
    }

    /**
     * {@inheritDoc}
     */
    public function getReserve4()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getReserve4', array());

        return parent::getReserve4();
    }

    /**
     * {@inheritDoc}
     */
    public function setReserve5($reserve5)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setReserve5', array($reserve5));

        return parent::setReserve5($reserve5);
    }

    /**
     * {@inheritDoc}
     */
    public function getReserve5()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getReserve5', array());

        return parent::getReserve5();
    }

    /**
     * {@inheritDoc}
     */
    public function setVideoid($videoid)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVideoid', array($videoid));

        return parent::setVideoid($videoid);
    }

    /**
     * {@inheritDoc}
     */
    public function getVideoid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVideoid', array());

        return parent::getVideoid();
    }

    /**
     * {@inheritDoc}
     */
    public function setPhotoid($photoid)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPhotoid', array($photoid));

        return parent::setPhotoid($photoid);
    }

    /**
     * {@inheritDoc}
     */
    public function getPhotoid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPhotoid', array());

        return parent::getPhotoid();
    }

    /**
     * {@inheritDoc}
     */
    public function setLocalid($localid)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLocalid', array($localid));

        return parent::setLocalid($localid);
    }

    /**
     * {@inheritDoc}
     */
    public function getLocalid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLocalid', array());

        return parent::getLocalid();
    }

    /**
     * {@inheritDoc}
     */
    public function setLocalsitecode($localsitecode)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLocalsitecode', array($localsitecode));

        return parent::setLocalsitecode($localsitecode);
    }

    /**
     * {@inheritDoc}
     */
    public function getLocalsitecode()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLocalsitecode', array());

        return parent::getLocalsitecode();
    }

    /**
     * {@inheritDoc}
     */
    public function setLocalcreatedate($localcreatedate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLocalcreatedate', array($localcreatedate));

        return parent::setLocalcreatedate($localcreatedate);
    }

    /**
     * {@inheritDoc}
     */
    public function getLocalcreatedate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLocalcreatedate', array());

        return parent::getLocalcreatedate();
    }

    /**
     * {@inheritDoc}
     */
    public function setIsapproved($isapproved)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsapproved', array($isapproved));

        return parent::setIsapproved($isapproved);
    }

    /**
     * {@inheritDoc}
     */
    public function getIsapproved()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIsapproved', array());

        return parent::getIsapproved();
    }

    /**
     * {@inheritDoc}
     */
    public function setApproveddate($approveddate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setApproveddate', array($approveddate));

        return parent::setApproveddate($approveddate);
    }

    /**
     * {@inheritDoc}
     */
    public function getApproveddate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getApproveddate', array());

        return parent::getApproveddate();
    }

    /**
     * {@inheritDoc}
     */
    public function setApproveduser($approveduser)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setApproveduser', array($approveduser));

        return parent::setApproveduser($approveduser);
    }

    /**
     * {@inheritDoc}
     */
    public function getApproveduser()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getApproveduser', array());

        return parent::getApproveduser();
    }

    /**
     * {@inheritDoc}
     */
    public function setIssentemail($issentemail)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIssentemail', array($issentemail));

        return parent::setIssentemail($issentemail);
    }

    /**
     * {@inheritDoc}
     */
    public function getIssentemail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIssentemail', array());

        return parent::getIssentemail();
    }

    /**
     * {@inheritDoc}
     */
    public function setIssentsns($issentsns)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIssentsns', array($issentsns));

        return parent::setIssentsns($issentsns);
    }

    /**
     * {@inheritDoc}
     */
    public function getIssentsns()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIssentsns', array());

        return parent::getIssentsns();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatedate($createdate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedate', array($createdate));

        return parent::setCreatedate($createdate);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedate', array());

        return parent::getCreatedate();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreateuser($createuser)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreateuser', array($createuser));

        return parent::setCreateuser($createuser);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreateuser()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreateuser', array());

        return parent::getCreateuser();
    }

    /**
     * {@inheritDoc}
     */
    public function setUpdatedate($updatedate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUpdatedate', array($updatedate));

        return parent::setUpdatedate($updatedate);
    }

    /**
     * {@inheritDoc}
     */
    public function getUpdatedate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUpdatedate', array());

        return parent::getUpdatedate();
    }

    /**
     * {@inheritDoc}
     */
    public function setUpdateuser($updateuser)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUpdateuser', array($updateuser));

        return parent::setUpdateuser($updateuser);
    }

    /**
     * {@inheritDoc}
     */
    public function getUpdateuser()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUpdateuser', array());

        return parent::getUpdateuser();
    }

    /**
     * {@inheritDoc}
     */
    public function setValid($valid)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setValid', array($valid));

        return parent::setValid($valid);
    }

    /**
     * {@inheritDoc}
     */
    public function getValid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getValid', array());

        return parent::getValid();
    }

    /**
     * {@inheritDoc}
     */
    public function setIsfavorite($isfavorite)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsfavorite', array($isfavorite));

        return parent::setIsfavorite($isfavorite);
    }

    /**
     * {@inheritDoc}
     */
    public function getIsfavorite()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIsfavorite', array());

        return parent::getIsfavorite();
    }

    /**
     * {@inheritDoc}
     */
    public function setProjectcode($projectcode)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProjectcode', array($projectcode));

        return parent::setProjectcode($projectcode);
    }

    /**
     * {@inheritDoc}
     */
    public function getProjectcode()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProjectcode', array());

        return parent::getProjectcode();
    }

}
