<?php

namespace DoctrineProxies\__CG__;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Emaillog extends \Emaillog implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Emaillog' . "\0" . 'id', '' . "\0" . 'Emaillog' . "\0" . 'accesscode', '' . "\0" . 'Emaillog' . "\0" . 'shareaccesscode', '' . "\0" . 'Emaillog' . "\0" . 'email', '' . "\0" . 'Emaillog' . "\0" . 'isvalidemail', '' . "\0" . 'Emaillog' . "\0" . 'issent', '' . "\0" . 'Emaillog' . "\0" . 'sentdate', '' . "\0" . 'Emaillog' . "\0" . 'isopened', '' . "\0" . 'Emaillog' . "\0" . 'openeddate', '' . "\0" . 'Emaillog' . "\0" . 'shorturl', '' . "\0" . 'Emaillog' . "\0" . 'reserve1', '' . "\0" . 'Emaillog' . "\0" . 'reserve2', '' . "\0" . 'Emaillog' . "\0" . 'reserve3', '' . "\0" . 'Emaillog' . "\0" . 'reserve4', '' . "\0" . 'Emaillog' . "\0" . 'reserve5', '' . "\0" . 'Emaillog' . "\0" . 'reserve6', '' . "\0" . 'Emaillog' . "\0" . 'reserve7', '' . "\0" . 'Emaillog' . "\0" . 'reserve8', '' . "\0" . 'Emaillog' . "\0" . 'reserve9', '' . "\0" . 'Emaillog' . "\0" . 'reserve10', '' . "\0" . 'Emaillog' . "\0" . 'edmmedia', '' . "\0" . 'Emaillog' . "\0" . 'createdate', '' . "\0" . 'Emaillog' . "\0" . 'createuser', '' . "\0" . 'Emaillog' . "\0" . 'updatedate', '' . "\0" . 'Emaillog' . "\0" . 'updateuser', '' . "\0" . 'Emaillog' . "\0" . 'valid', '' . "\0" . 'Emaillog' . "\0" . 'userid');
        }

        return array('__isInitialized__', '' . "\0" . 'Emaillog' . "\0" . 'id', '' . "\0" . 'Emaillog' . "\0" . 'accesscode', '' . "\0" . 'Emaillog' . "\0" . 'shareaccesscode', '' . "\0" . 'Emaillog' . "\0" . 'email', '' . "\0" . 'Emaillog' . "\0" . 'isvalidemail', '' . "\0" . 'Emaillog' . "\0" . 'issent', '' . "\0" . 'Emaillog' . "\0" . 'sentdate', '' . "\0" . 'Emaillog' . "\0" . 'isopened', '' . "\0" . 'Emaillog' . "\0" . 'openeddate', '' . "\0" . 'Emaillog' . "\0" . 'shorturl', '' . "\0" . 'Emaillog' . "\0" . 'reserve1', '' . "\0" . 'Emaillog' . "\0" . 'reserve2', '' . "\0" . 'Emaillog' . "\0" . 'reserve3', '' . "\0" . 'Emaillog' . "\0" . 'reserve4', '' . "\0" . 'Emaillog' . "\0" . 'reserve5', '' . "\0" . 'Emaillog' . "\0" . 'reserve6', '' . "\0" . 'Emaillog' . "\0" . 'reserve7', '' . "\0" . 'Emaillog' . "\0" . 'reserve8', '' . "\0" . 'Emaillog' . "\0" . 'reserve9', '' . "\0" . 'Emaillog' . "\0" . 'reserve10', '' . "\0" . 'Emaillog' . "\0" . 'edmmedia', '' . "\0" . 'Emaillog' . "\0" . 'createdate', '' . "\0" . 'Emaillog' . "\0" . 'createuser', '' . "\0" . 'Emaillog' . "\0" . 'updatedate', '' . "\0" . 'Emaillog' . "\0" . 'updateuser', '' . "\0" . 'Emaillog' . "\0" . 'valid', '' . "\0" . 'Emaillog' . "\0" . 'userid');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Emaillog $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setAccesscode($accesscode)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAccesscode', array($accesscode));

        return parent::setAccesscode($accesscode);
    }

    /**
     * {@inheritDoc}
     */
    public function getAccesscode()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAccesscode', array());

        return parent::getAccesscode();
    }

    /**
     * {@inheritDoc}
     */
    public function setShareaccesscode($shareaccesscode)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setShareaccesscode', array($shareaccesscode));

        return parent::setShareaccesscode($shareaccesscode);
    }

    /**
     * {@inheritDoc}
     */
    public function getShareaccesscode()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getShareaccesscode', array());

        return parent::getShareaccesscode();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmail($email)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmail', array($email));

        return parent::setEmail($email);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmail', array());

        return parent::getEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function setIsvalidemail($isvalidemail)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsvalidemail', array($isvalidemail));

        return parent::setIsvalidemail($isvalidemail);
    }

    /**
     * {@inheritDoc}
     */
    public function getIsvalidemail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIsvalidemail', array());

        return parent::getIsvalidemail();
    }

    /**
     * {@inheritDoc}
     */
    public function setIssent($issent)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIssent', array($issent));

        return parent::setIssent($issent);
    }

    /**
     * {@inheritDoc}
     */
    public function getIssent()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIssent', array());

        return parent::getIssent();
    }

    /**
     * {@inheritDoc}
     */
    public function setSentdate($sentdate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSentdate', array($sentdate));

        return parent::setSentdate($sentdate);
    }

    /**
     * {@inheritDoc}
     */
    public function getSentdate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSentdate', array());

        return parent::getSentdate();
    }

    /**
     * {@inheritDoc}
     */
    public function setIsopened($isopened)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsopened', array($isopened));

        return parent::setIsopened($isopened);
    }

    /**
     * {@inheritDoc}
     */
    public function getIsopened()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIsopened', array());

        return parent::getIsopened();
    }

    /**
     * {@inheritDoc}
     */
    public function setOpeneddate($openeddate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOpeneddate', array($openeddate));

        return parent::setOpeneddate($openeddate);
    }

    /**
     * {@inheritDoc}
     */
    public function getOpeneddate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOpeneddate', array());

        return parent::getOpeneddate();
    }

    /**
     * {@inheritDoc}
     */
    public function setShorturl($shorturl)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setShorturl', array($shorturl));

        return parent::setShorturl($shorturl);
    }

    /**
     * {@inheritDoc}
     */
    public function getShorturl()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getShorturl', array());

        return parent::getShorturl();
    }

    /**
     * {@inheritDoc}
     */
    public function setReserve1($reserve1)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setReserve1', array($reserve1));

        return parent::setReserve1($reserve1);
    }

    /**
     * {@inheritDoc}
     */
    public function getReserve1()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getReserve1', array());

        return parent::getReserve1();
    }

    /**
     * {@inheritDoc}
     */
    public function setReserve2($reserve2)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setReserve2', array($reserve2));

        return parent::setReserve2($reserve2);
    }

    /**
     * {@inheritDoc}
     */
    public function getReserve2()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getReserve2', array());

        return parent::getReserve2();
    }

    /**
     * {@inheritDoc}
     */
    public function setReserve3($reserve3)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setReserve3', array($reserve3));

        return parent::setReserve3($reserve3);
    }

    /**
     * {@inheritDoc}
     */
    public function getReserve3()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getReserve3', array());

        return parent::getReserve3();
    }

    /**
     * {@inheritDoc}
     */
    public function setReserve4($reserve4)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setReserve4', array($reserve4));

        return parent::setReserve4($reserve4);
    }

    /**
     * {@inheritDoc}
     */
    public function getReserve4()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getReserve4', array());

        return parent::getReserve4();
    }

    /**
     * {@inheritDoc}
     */
    public function setReserve5($reserve5)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setReserve5', array($reserve5));

        return parent::setReserve5($reserve5);
    }

    /**
     * {@inheritDoc}
     */
    public function getReserve5()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getReserve5', array());

        return parent::getReserve5();
    }

    /**
     * {@inheritDoc}
     */
    public function setReserve6($reserve6)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setReserve6', array($reserve6));

        return parent::setReserve6($reserve6);
    }

    /**
     * {@inheritDoc}
     */
    public function getReserve6()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getReserve6', array());

        return parent::getReserve6();
    }

    /**
     * {@inheritDoc}
     */
    public function setReserve7($reserve7)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setReserve7', array($reserve7));

        return parent::setReserve7($reserve7);
    }

    /**
     * {@inheritDoc}
     */
    public function getReserve7()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getReserve7', array());

        return parent::getReserve7();
    }

    /**
     * {@inheritDoc}
     */
    public function setReserve8($reserve8)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setReserve8', array($reserve8));

        return parent::setReserve8($reserve8);
    }

    /**
     * {@inheritDoc}
     */
    public function getReserve8()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getReserve8', array());

        return parent::getReserve8();
    }

    /**
     * {@inheritDoc}
     */
    public function setReserve9($reserve9)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setReserve9', array($reserve9));

        return parent::setReserve9($reserve9);
    }

    /**
     * {@inheritDoc}
     */
    public function getReserve9()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getReserve9', array());

        return parent::getReserve9();
    }

    /**
     * {@inheritDoc}
     */
    public function setReserve10($reserve10)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setReserve10', array($reserve10));

        return parent::setReserve10($reserve10);
    }

    /**
     * {@inheritDoc}
     */
    public function getReserve10()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getReserve10', array());

        return parent::getReserve10();
    }

    /**
     * {@inheritDoc}
     */
    public function setEdmmedia($edmmedia)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEdmmedia', array($edmmedia));

        return parent::setEdmmedia($edmmedia);
    }

    /**
     * {@inheritDoc}
     */
    public function getEdmmedia()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEdmmedia', array());

        return parent::getEdmmedia();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatedate($createdate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedate', array($createdate));

        return parent::setCreatedate($createdate);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedate', array());

        return parent::getCreatedate();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreateuser($createuser)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreateuser', array($createuser));

        return parent::setCreateuser($createuser);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreateuser()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreateuser', array());

        return parent::getCreateuser();
    }

    /**
     * {@inheritDoc}
     */
    public function setUpdatedate($updatedate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUpdatedate', array($updatedate));

        return parent::setUpdatedate($updatedate);
    }

    /**
     * {@inheritDoc}
     */
    public function getUpdatedate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUpdatedate', array());

        return parent::getUpdatedate();
    }

    /**
     * {@inheritDoc}
     */
    public function setUpdateuser($updateuser)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUpdateuser', array($updateuser));

        return parent::setUpdateuser($updateuser);
    }

    /**
     * {@inheritDoc}
     */
    public function getUpdateuser()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUpdateuser', array());

        return parent::getUpdateuser();
    }

    /**
     * {@inheritDoc}
     */
    public function setValid($valid)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setValid', array($valid));

        return parent::setValid($valid);
    }

    /**
     * {@inheritDoc}
     */
    public function getValid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getValid', array());

        return parent::getValid();
    }

    /**
     * {@inheritDoc}
     */
    public function setUserid(\User $userid = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUserid', array($userid));

        return parent::setUserid($userid);
    }

    /**
     * {@inheritDoc}
     */
    public function getUserid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUserid', array());

        return parent::getUserid();
    }

}
